language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements/development.txt
before_script:
- psql -c 'CREATE DATABASE yebimom;' -U postgres
script:
- npm install -g bower grunt-cli
- npm install
- gem install sass
- grunt bowercopy sass
- python manage.py collectstatic --noinput --ignore '*.sass'
- pep8
- python manage.py makemigrations users centers events reviews
- python manage.py migrate
- python manage.py loaddata regions facilities
- python manage.py test -v2
deploy:
  provider: heroku
  app: yebimom-dev
  api_key:
    secure: EZpVqKISJB+tv0bBDJBEJeKVeZuGdJC4Dh5MOev+ckV2FXfdRmcKTA/VPoYBeIYLnmMlL3kPjIxXTeqdkGEkBXSNfZV9ClJEPN+pRjwkNmVji+H+51c1jjE890dI6YGXxpz0k0Q72JfaLTn3tGScLjtgg7IYaxR7LaM6+VNZHfM=
  on: develop
notifications:
  slack: molang:iOlv6ne427evuLd1S02CiLFD
  email:
    on_success: never
    on_failure: always
