language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements/development.txt
before_script:
- psql -c 'CREATE DATABASE yebimom;' -U postgres
script:
- npm install -g bower grunt-cli
- npm install
- gem install compass
- grunt bowercopy compass
- pep8
- python yebimom/manage.py makemigrations users centers events reviews
- python yebimom/manage.py migrate
- python yebimom/manage.py loaddata regions facilities
- python yebimom/manage.py test yebimom/ -v2
deploy:
  provider: heroku
  api_key:
    secure: RI2daRfO/7uy221oO88Ts/hYENSPMyds8hFndOcIPezXsK+TUypz4PaJ3jIjWD/L5YES59t52BT6USOE1HFeQarsZ23ZSD7PGegXqiKZCWqaTgqsUgWiXXoJPZWsEfGViB5sSYekQS6tJsFEYvAfl0Qo4Ai1UcF5B34XCdsUFDE=
  app: yebimom-dev
  on:
    repo: yebimom/yebimom
    all_branches: true
notifications:
  slack: molang:iOlv6ne427evuLd1S02CiLFD
  email:
    on_success: never
    on_failure: always
